project:
  type: website
  output-dir: docs
  resources:
    - images/**
    - google250eb84d152623e9.html
  
website:
  title: "Karthik Prabhu Palimar"
  description: "Physics PhD | CMB Cosmology, Machine Learning, Generative Models, Statistical Inference"
  site-url: "https://karthikprabhu22.github.io"
  open-graph: true

  
  navbar:
    title: false
    search: false
    left:
      - text: "Home"
        href: index.qmd
      - text: "Papers"
        href: papers.qmd
      - text: "Projects"
        href: projects.qmd
  page-footer:
    left: "Copyright 2025, Karthik Prabhu Palimar."
  image: images/avatar.jpg

# Global HTML metadata (applies to all pages)
metadata:
  robots: "index, follow"
  lang: "en"

format:
  html:
    backgroundcolor" : "#eeffee"
    theme:
      light: flatly
    css: styles.css
    markdown:
      extensions:
        - raw_html
    toc: false
    smooth-scroll: true
    link-external-icon: true
    canonical-url: true